FROM openjdk:17-jdk-alpine AS builder
WORKDIR /app
COPY src ./src
COPY .mvn ./.mvn
COPY mvnw .
COPY pom.xml .
RUN chmod 700 mvnw
RUN ./mvnw clean package -DskipTests

FROM openjdk:17-jdk-alpine
WORKDIR /app
COPY --from=builder app/target/loan-service.jar .
EXPOSE 8080
ENTRYPOINT ["java","-Dspring.profiles.active=dev","-jar","loan-service.jar"]